modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Rainy1127/Tinkers-Construct-1.21.1-Port-Unofficial/issues"
logoFile="Mantle.png"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    authors="${mod_authors}"
    description='''${mod_description}'''
    displayURL="https://github.com/Rainy1127/Tinkers-Construct-1.21.1-Port-Unofficial/"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
